[build]
  command = "ng build --configuration=production"
  publish = "dist/aleksander-nikolli-developer/browser"

[[plugins]]
  package = "@netlify/angular-runtime"
  # disable = false # Lascia questa riga commentata o rimuovila se non vuoi disabilitare il plugin